services:
  - type: web
    name: nl-to-sql-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers
